language: node_js
node_js:
  - "stable"
install:
    - npm install
cache:
  directories:
  - node_modules
script:
    - npm run build-lib
    - npm test
    - npm run coverage
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"